export enum RouteName {
  HomePage = "/",
  activityView = "/activity",
  auctionsView = "/auctions",
  marketplace = "/marketplace",
  MarketplaceWithFilter = "/multi-collection-marketplace",
  AllNftFilter = "/all-nfts",
  StructuralLegaciesFilter = "/structural-legacies",
  SystemArchitectureFilter = "/system-architecture",
  HomeDesignFilter = "/home-designs",
  ProductsFilter = "/products",
  AlgorithmFilter = "/algorithm",
  ClaimQubes = "/claimqubes",
  MyCollection = "/mycollection",
  sell = "/sell",
  customToken = "/custom-token-marketplace",
  multipleCollection = "",
  marketplaceWithUrl = "/marketplace-with-url",
  multipleCurrencyMarketplace = "/multi-currency-marketplace",
  multipleCurrencySell = "/multi-currency-sell",
  addMyCollections = "/addmycollection",
  practice = "/practice",
}
