export enum RouteName {
  HomePage = "/",
  activityView = "/activity",
  auctionsView = "/auctions",
  marketplace = "/marketplace",
  MarketplaceWithFilter = "/multi-collection-marketplace",
  StructuralLegaciesFilter = "/structural-legacies",
  SystemArchitectureFilter = "/system-architecture",
  HomeDesignFilter = "/home-designs",
  ProductsFilter = "/products",
  ClaimQubes = "/claimqubes",
  MyCollection = "/mycollection",
  sell = "/poZxCBHNsdSwErewqHQSELLlkGfsfGhJZCcxsDDxcdaswevJCiGopcxasedWarDfiGderUrghh",
  customToken = "/custom-token-marketplace",
  multipleCollection = "",
  marketplaceWithUrl = "/marketplace-with-url",
  multipleCurrencyMarketplace = "/multi-currency-marketplace",
  multipleCurrencySell = "/multi-currency-sell",
  addMyCollections = "/addmycollection"
}
